# We appreciate all donations towards the development of Steroid4.0

github: angelexevior
bpc: 5XXSy8akLrRJec67UVRiNmSntkwzesJWQp9c29t3sMZfJnqUfn8FcMtiZ8vs8puvJPQYzypNv1WHUyLqFx3XM1Uz
btc: bc1qtmd29pv2mu6latsq555prnzfvppdvq0mjfctg5
eth: 0x6C36F8985Be53A8DF6D7b0756E0CD97cE1445D8F
