-- steroidV2 Database Schema
-- Rebuilt from S4QL reference — no LOCK TABLES, InnoDB, utf8mb4, clean indexes
-- Generated by LARS for Steroid V2 Rebuild

SET FOREIGN_KEY_CHECKS = 0;
SET sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- blocks
CREATE TABLE IF NOT EXISTS `blocks` (
  `id`           varbinary(128)  NOT NULL,
  `generator`    varbinary(128)  NOT NULL,
  `height`       bigint(20)      NOT NULL,
  `date`         int(11)         NOT NULL,
  `nonce`        varbinary(128)  NOT NULL,
  `signature`    varbinary(256)  NOT NULL,
  `difficulty`   varchar(64)     COLLATE utf8mb4_bin NOT NULL,
  `argon`        varbinary(128)  NOT NULL,
  `transactions` int(11)         NOT NULL DEFAULT 0,
  PRIMARY KEY (`height`),
  UNIQUE KEY `uq_block_id`   (`id`),
  KEY `idx_generator`        (`generator`),
  KEY `idx_date`             (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- accounts
CREATE TABLE IF NOT EXISTS `accounts` (
  `id`         varbinary(128)  NOT NULL,
  `public_key` varbinary(1024) NOT NULL,
  `block`      varbinary(128)  NOT NULL,
  `balance`    decimal(20,8)   NOT NULL DEFAULT 0.00000000,
  `alias`      varchar(32)     COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_block`  (`block`),
  KEY `idx_alias`  (`alias`),
  KEY `idx_pubkey` (`public_key`(767)),
  CONSTRAINT `fk_accounts_block`
    FOREIGN KEY (`block`) REFERENCES `blocks` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- transactions
CREATE TABLE IF NOT EXISTS `transactions` (
  `id`         varbinary(128)  NOT NULL,
  `block`      varbinary(128)  NOT NULL,
  `height`     bigint(20)      NOT NULL,
  `src`        varbinary(128)  NOT NULL,
  `dst`        varbinary(128)  NOT NULL,
  `val`        decimal(20,8)   NOT NULL DEFAULT 0.00000000,
  `fee`        decimal(20,8)   NOT NULL DEFAULT 0.00000000,
  `signature`  varbinary(256)  NOT NULL,
  `version`    tinyint(4)      NOT NULL DEFAULT 0,
  `message`    varchar(256)    COLLATE utf8mb4_bin DEFAULT '',
  `date`       int(11)         NOT NULL,
  `public_key` varbinary(1024) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_block`          (`block`),
  KEY `idx_height`         (`height`),
  KEY `idx_src`            (`src`),
  KEY `idx_dst`            (`dst`),
  KEY `idx_pubkey_height`  (`public_key`(130), `height`),
  KEY `idx_dst_height`     (`dst`, `height`),
  KEY `idx_version_height` (`version`, `height`),
  CONSTRAINT `fk_tx_height`
    FOREIGN KEY (`height`) REFERENCES `blocks` (`height`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mempool
CREATE TABLE IF NOT EXISTS `mempool` (
  `id`         varbinary(128)  NOT NULL,
  `height`     bigint(20)      NOT NULL,
  `src`        varbinary(128)  NOT NULL,
  `dst`        varbinary(128)  NOT NULL,
  `val`        decimal(20,8)   NOT NULL DEFAULT 0.00000000,
  `fee`        decimal(20,8)   NOT NULL DEFAULT 0.00000000,
  `signature`  varbinary(256)  NOT NULL,
  `version`    tinyint(4)      NOT NULL,
  `message`    varchar(256)    COLLATE utf8mb4_bin DEFAULT '',
  `public_key` varbinary(1024) NOT NULL,
  `date`       bigint(20)      NOT NULL,
  `peer`       varchar(64)     COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_height` (`height`),
  KEY `idx_src`    (`src`),
  KEY `idx_peer`   (`peer`),
  KEY `idx_val`    (`val`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- masternode
CREATE TABLE IF NOT EXISTS `masternode` (
  `public_key`    varbinary(512) NOT NULL,
  `height`        int(11)        NOT NULL,
  `ip`            varchar(16)    COLLATE utf8mb4_bin NOT NULL,
  `last_won`      int(11)        NOT NULL DEFAULT 0,
  `blacklist`     int(11)        NOT NULL DEFAULT 0,
  `fails`         int(11)        NOT NULL DEFAULT 0,
  `status`        tinyint(4)     NOT NULL DEFAULT 1,
  `vote_key`      varbinary(512) DEFAULT NULL,
  `cold_last_won` int(11)        NOT NULL DEFAULT 0,
  `voted`         tinyint(4)     NOT NULL DEFAULT 0,
  PRIMARY KEY (`public_key`),
  KEY `idx_last_won`      (`last_won`),
  KEY `idx_status`        (`status`),
  KEY `idx_blacklist`     (`blacklist`),
  KEY `idx_height`        (`height`),
  KEY `idx_vote_key`      (`vote_key`),
  KEY `idx_cold_last_won` (`cold_last_won`),
  KEY `idx_voted`         (`voted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- masternode_rewards
CREATE TABLE IF NOT EXISTS `masternode_rewards` (
  `id`         int(11)        NOT NULL AUTO_INCREMENT,
  `public_key` varbinary(512) NOT NULL,
  `height`     bigint(20)     NOT NULL,
  `reward`     decimal(20,8)  NOT NULL DEFAULT 0.00000000,
  `date`       int(11)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pubkey` (`public_key`),
  KEY `idx_height` (`height`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- peers
CREATE TABLE IF NOT EXISTS `peers` (
  `id`          int(11)     NOT NULL AUTO_INCREMENT,
  `hostname`    varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `blacklisted` int(11)     NOT NULL DEFAULT 0,
  `ping`        int(11)     NOT NULL DEFAULT 0,
  `reserve`     tinyint(4)  NOT NULL DEFAULT 1,
  `ip`          varchar(80) NOT NULL,
  `fails`       tinyint(4)  NOT NULL DEFAULT 0,
  `stuckfail`   tinyint(4)  NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hostname`     (`hostname`),
  UNIQUE KEY `uq_ip`           (`ip`),
  KEY `idx_blacklisted`        (`blacklisted`),
  KEY `idx_ping`               (`ping`),
  KEY `idx_reserve`            (`reserve`),
  KEY `idx_stuckfail`          (`stuckfail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- assets
CREATE TABLE IF NOT EXISTS `assets` (
  `id`            varbinary(128) NOT NULL,
  `max_supply`    bigint(18)     NOT NULL DEFAULT 0,
  `tradable`      tinyint(1)     NOT NULL DEFAULT 1,
  `price`         decimal(20,8)  NOT NULL DEFAULT 0.00000000,
  `dividend_only` tinyint(1)     NOT NULL DEFAULT 0,
  `auto_dividend` tinyint(1)     NOT NULL DEFAULT 0,
  `allow_bid`     tinyint(1)     NOT NULL DEFAULT 1,
  `height`        int(11)        NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_height`   (`height`),
  KEY `idx_tradable` (`tradable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- assets_balance
CREATE TABLE IF NOT EXISTS `assets_balance` (
  `account` varbinary(128) NOT NULL,
  `asset`   varbinary(128) NOT NULL,
  `balance` decimal(20,8)  NOT NULL DEFAULT 0.00000000,
  PRIMARY KEY (`account`, `asset`),
  KEY `idx_asset`   (`asset`),
  KEY `idx_account` (`account`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- assets_market
CREATE TABLE IF NOT EXISTS `assets_market` (
  `id`         varchar(128)  COLLATE utf8mb4_bin NOT NULL,
  `account`    varbinary(128) NOT NULL,
  `asset`      varbinary(128) NOT NULL,
  `price`      decimal(20,8)  NOT NULL,
  `date`       int(11)        NOT NULL,
  `status`     tinyint(1)     NOT NULL DEFAULT 0,
  `type`       enum('bid','ask') COLLATE utf8mb4_bin NOT NULL DEFAULT 'bid',
  `val`        bigint(18)     NOT NULL,
  `val_done`   bigint(18)     NOT NULL DEFAULT 0,
  `cancelable` tinyint(1)     NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_account` (`account`),
  KEY `idx_asset`   (`asset`),
  KEY `idx_status`  (`status`),
  KEY `idx_type`    (`type`),
  KEY `idx_date`    (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- votes
CREATE TABLE IF NOT EXISTS `votes` (
  `id`  varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `nfo` varchar(64)  NOT NULL,
  `val` int(11)      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_nfo` (`nfo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- config
CREATE TABLE IF NOT EXISTS `config` (
  `cfg` varchar(30)  COLLATE utf8mb4_bin NOT NULL,
  `val` varchar(200) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`cfg`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- heartbeat
CREATE TABLE IF NOT EXISTS `heartbeat` (
  `beep`      tinyint(1) NOT NULL DEFAULT 1,
  `timestamp` datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- logs
CREATE TABLE IF NOT EXISTS `logs` (
  `id`          int(11)        NOT NULL AUTO_INCREMENT,
  `transaction` varbinary(512) DEFAULT NULL,
  `block`       varbinary(512) DEFAULT NULL,
  `json`        text           DEFAULT NULL,
  `created_at`  datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_transaction` (`transaction`),
  KEY `idx_block`       (`block`),
  KEY `idx_created_at`  (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apilog
CREATE TABLE IF NOT EXISTS `apilog` (
  `id`       int(11)      NOT NULL AUTO_INCREMENT,
  `endpoint` varchar(128) NOT NULL,
  `ip`       varchar(80)  NOT NULL,
  `date`     int(11)      NOT NULL,
  `response` smallint(6)  NOT NULL DEFAULT 200,
  PRIMARY KEY (`id`),
  KEY `idx_endpoint` (`endpoint`),
  KEY `idx_ip`       (`ip`),
  KEY `idx_date`     (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- wallet_stats
CREATE TABLE IF NOT EXISTS `wallet_stats` (
  `id`      int(11)      NOT NULL AUTO_INCREMENT,
  `stat`    varchar(64)  COLLATE utf8mb4_bin NOT NULL,
  `val`     varchar(200) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `updated` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stat` (`stat`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- blockstats view
CREATE OR REPLACE VIEW `blockstats` AS
  SELECT
    (a.`date` - b.`date`)   AS `blocktime`,
    a.`height`              AS `height`,
    a.`date`                AS `timestamp`,
    FROM_UNIXTIME(a.`date`) AS `date_time`,
    NOW()                   AS `currenttime`,
    a.`difficulty`          AS `difficulty`
  FROM `blocks` a
  LEFT JOIN `blocks` b ON b.`height` = (a.`height` - 1)
  ORDER BY a.`height` DESC
  LIMIT 100;

SET FOREIGN_KEY_CHECKS = 1;
