server {
    listen 80;
    listen 443 ssl;
    server_name steroidv2.steroid.io;

    ssl_certificate     /etc/ssl/pool.pem;
    ssl_certificate_key /etc/ssl/pool.key;

    root  /data/wwwroot/steroidV2;
    index index.php;

    access_log /data/wwwlogs/steroidv2.steroid.io_access.log;
    error_log  /data/wwwlogs/steroidv2.steroid.io_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass  unix:/dev/shm/php-cgi.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include       fastcgi_params;
    }

    location ~ /\. { deny all; }
    location ~* \.(sql|log|env|json|md|lock|git)$ { deny all; }
}
