// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steroid/vrf/v1/genesis.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the x/vrf module's genesis state.
type GenesisState struct {
	ValidatorVrfKeys []*ValidatorVRFKey `protobuf:"bytes,1,rep,name=validator_vrf_keys,json=validatorVrfKeys,proto3" json:"validator_vrf_keys,omitempty"`
	// last_vrf_output is the most recent accepted proposer's VRF output
	// (Decision 3's prev_vrf_output for the next height's seed). Empty at
	// genesis.
	LastVrfOutput []byte `protobuf:"bytes,2,opt,name=last_vrf_output,json=lastVrfOutput,proto3" json:"last_vrf_output,omitempty"`
	// last_tx_accumulator is the previous block's running tx-hash accumulator
	// (Decision 3). Defaults to SHA256(empty) at genesis (the empty-block case).
	LastTxAccumulator []byte `protobuf:"bytes,3,opt,name=last_tx_accumulator,json=lastTxAccumulator,proto3" json:"last_tx_accumulator,omitempty"`
	// last_accepted_time_unix_nano is the timestamp of the most recently
	// accepted block, used to evaluate the fallback window (see
	// keeper.ShouldAcceptFallback). Set to genesis time at genesis.
	LastAcceptedTimeUnixNano int64 `protobuf:"varint,4,opt,name=last_accepted_time_unix_nano,json=lastAcceptedTimeUnixNano,proto3" json:"last_accepted_time_unix_nano,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_967e37577fa8a688, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetValidatorVrfKeys() []*ValidatorVRFKey {
	if m != nil {
		return m.ValidatorVrfKeys
	}
	return nil
}

func (m *GenesisState) GetLastVrfOutput() []byte {
	if m != nil {
		return m.LastVrfOutput
	}
	return nil
}

func (m *GenesisState) GetLastTxAccumulator() []byte {
	if m != nil {
		return m.LastTxAccumulator
	}
	return nil
}

func (m *GenesisState) GetLastAcceptedTimeUnixNano() int64 {
	if m != nil {
		return m.LastAcceptedTimeUnixNano
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "steroid.vrf.v1.GenesisState")
}

func init() { proto.RegisterFile("steroid/vrf/v1/genesis.proto", fileDescriptor_967e37577fa8a688) }

var fileDescriptor_967e37577fa8a688 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0x05, 0xf0, 0xfa, 0xeb, 0x27, 0x86, 0x50, 0xfe, 0x85, 0x25, 0xaa, 0xaa, 0x50, 0x31, 0xa0,
	0x2e, 0xd8, 0x14, 0x98, 0x91, 0xca, 0x00, 0x42, 0x15, 0x20, 0x85, 0x92, 0x81, 0x25, 0x72, 0xd3,
	0x9b, 0x62, 0xd1, 0xc4, 0x91, 0x73, 0x13, 0x39, 0x6f, 0xc1, 0x63, 0x31, 0x76, 0x64, 0x44, 0xcd,
	0x33, 0xb0, 0xa3, 0x98, 0x00, 0x82, 0xd5, 0xe7, 0x77, 0x8f, 0xe4, 0x63, 0xf5, 0x32, 0x04, 0x25,
	0xc5, 0x8c, 0x15, 0x2a, 0x62, 0xc5, 0x90, 0xcd, 0x21, 0x81, 0x4c, 0x64, 0x34, 0x55, 0x12, 0xa5,
	0xbd, 0xd9, 0xa4, 0xb4, 0x50, 0x11, 0x2d, 0x86, 0xdd, 0xee, 0x1f, 0x8d, 0x65, 0x0a, 0x8d, 0xdd,
	0x7f, 0x27, 0x56, 0xe7, 0xf2, 0xf3, 0xfa, 0x0e, 0x39, 0x82, 0x7d, 0x6d, 0xd9, 0x05, 0x5f, 0x88,
	0x19, 0x47, 0xa9, 0x82, 0x42, 0x45, 0xc1, 0x13, 0x94, 0x99, 0x43, 0xfa, 0xed, 0xc1, 0xfa, 0xf1,
	0x1e, 0xfd, 0xdd, 0x4c, 0xfd, 0x2f, 0xe9, 0x7b, 0x17, 0x63, 0x28, 0xbd, 0xed, 0xef, 0x53, 0x5f,
	0x45, 0x63, 0x28, 0x33, 0xfb, 0xc0, 0xda, 0x5a, 0xf0, 0x0c, 0x4d, 0x93, 0xcc, 0x31, 0xcd, 0xd1,
	0xf9, 0xd7, 0x27, 0x83, 0x8e, 0xb7, 0x51, 0x3f, 0xfb, 0x2a, 0xba, 0x35, 0x8f, 0x36, 0xb5, 0x76,
	0x8d, 0x43, 0x1d, 0xf0, 0x30, 0xcc, 0xe3, 0x7c, 0x51, 0xb7, 0x38, 0x6d, 0x63, 0x77, 0xea, 0x68,
	0xa2, 0x47, 0x3f, 0x81, 0x7d, 0x66, 0xf5, 0x8c, 0xe7, 0x61, 0x08, 0x29, 0xc2, 0x2c, 0x40, 0x11,
	0x43, 0x90, 0x27, 0x42, 0x07, 0x09, 0x4f, 0xa4, 0xf3, 0xbf, 0x4f, 0x06, 0x6d, 0xcf, 0xa9, 0xcd,
	0xa8, 0x21, 0x13, 0x11, 0xc3, 0x7d, 0x22, 0xf4, 0x0d, 0x4f, 0xe4, 0xf9, 0xd5, 0xcb, 0xca, 0x25,
	0xcb, 0x95, 0x4b, 0xde, 0x56, 0x2e, 0x79, 0xae, 0xdc, 0xd6, 0xb2, 0x72, 0x5b, 0xaf, 0x95, 0xdb,
	0x7a, 0x60, 0x73, 0x81, 0x8f, 0xf9, 0x94, 0x86, 0x32, 0x66, 0x53, 0x80, 0x54, 0xa3, 0xe2, 0xac,
	0xf9, 0xf7, 0x61, 0x28, 0x15, 0x9c, 0xd2, 0x23, 0xa6, 0xcd, 0x96, 0x66, 0xc8, 0xe9, 0x9a, 0x59,
	0xf2, 0xe4, 0x23, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xbd, 0x1f, 0xeb, 0x95, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastAcceptedTimeUnixNano != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastAcceptedTimeUnixNano))
		i--
		dAtA[i] = 0x20
	}
	if len(m.LastTxAccumulator) > 0 {
		i -= len(m.LastTxAccumulator)
		copy(dAtA[i:], m.LastTxAccumulator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.LastTxAccumulator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LastVrfOutput) > 0 {
		i -= len(m.LastVrfOutput)
		copy(dAtA[i:], m.LastVrfOutput)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.LastVrfOutput)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorVrfKeys) > 0 {
		for iNdEx := len(m.ValidatorVrfKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorVrfKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorVrfKeys) > 0 {
		for _, e := range m.ValidatorVrfKeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.LastVrfOutput)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.LastTxAccumulator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LastAcceptedTimeUnixNano != 0 {
		n += 1 + sovGenesis(uint64(m.LastAcceptedTimeUnixNano))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorVrfKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorVrfKeys = append(m.ValidatorVrfKeys, &ValidatorVRFKey{})
			if err := m.ValidatorVrfKeys[len(m.ValidatorVrfKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastVrfOutput", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastVrfOutput = append(m.LastVrfOutput[:0], dAtA[iNdEx:postIndex]...)
			if m.LastVrfOutput == nil {
				m.LastVrfOutput = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTxAccumulator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastTxAccumulator = append(m.LastTxAccumulator[:0], dAtA[iNdEx:postIndex]...)
			if m.LastTxAccumulator == nil {
				m.LastTxAccumulator = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAcceptedTimeUnixNano", wireType)
			}
			m.LastAcceptedTimeUnixNano = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastAcceptedTimeUnixNano |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
