// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steroid/vrf/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryValidatorVRFKeyRequest struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryValidatorVRFKeyRequest) Reset()         { *m = QueryValidatorVRFKeyRequest{} }
func (m *QueryValidatorVRFKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorVRFKeyRequest) ProtoMessage()    {}
func (*QueryValidatorVRFKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17afe4692f4e80b8, []int{0}
}
func (m *QueryValidatorVRFKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorVRFKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorVRFKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorVRFKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorVRFKeyRequest.Merge(m, src)
}
func (m *QueryValidatorVRFKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorVRFKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorVRFKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorVRFKeyRequest proto.InternalMessageInfo

func (m *QueryValidatorVRFKeyRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

type QueryValidatorVRFKeyResponse struct {
	ValidatorVrfKey ValidatorVRFKey `protobuf:"bytes,1,opt,name=validator_vrf_key,json=validatorVrfKey,proto3" json:"validator_vrf_key"`
}

func (m *QueryValidatorVRFKeyResponse) Reset()         { *m = QueryValidatorVRFKeyResponse{} }
func (m *QueryValidatorVRFKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorVRFKeyResponse) ProtoMessage()    {}
func (*QueryValidatorVRFKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17afe4692f4e80b8, []int{1}
}
func (m *QueryValidatorVRFKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorVRFKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorVRFKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorVRFKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorVRFKeyResponse.Merge(m, src)
}
func (m *QueryValidatorVRFKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorVRFKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorVRFKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorVRFKeyResponse proto.InternalMessageInfo

func (m *QueryValidatorVRFKeyResponse) GetValidatorVrfKey() ValidatorVRFKey {
	if m != nil {
		return m.ValidatorVrfKey
	}
	return ValidatorVRFKey{}
}

func init() {
	proto.RegisterType((*QueryValidatorVRFKeyRequest)(nil), "steroid.vrf.v1.QueryValidatorVRFKeyRequest")
	proto.RegisterType((*QueryValidatorVRFKeyResponse)(nil), "steroid.vrf.v1.QueryValidatorVRFKeyResponse")
}

func init() { proto.RegisterFile("steroid/vrf/v1/query.proto", fileDescriptor_17afe4692f4e80b8) }

var fileDescriptor_17afe4692f4e80b8 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0x49, 0x2d,
	0xca, 0xcf, 0x4c, 0xd1, 0x2f, 0x2b, 0x4a, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0xca, 0xe9, 0x95, 0x15, 0xa5, 0xe9, 0x95,
	0x19, 0x4a, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0xa5, 0xf4, 0x41, 0x2c, 0x88, 0x2a, 0x29, 0x99,
	0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92,
	0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0xa8, 0x2c, 0xba, 0xf9, 0x25, 0x95, 0x05, 0xa9, 0x50, 0x39,
	0x25, 0x2f, 0x2e, 0xe9, 0x40, 0x90, 0x75, 0x61, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0xf9, 0x45,
	0x61, 0x41, 0x6e, 0xde, 0xa9, 0x95, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xda, 0x5c,
	0x82, 0x65, 0x30, 0x99, 0xf8, 0xc4, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x01, 0xb8, 0x84, 0x23, 0x44, 0x5c, 0xa9, 0x90, 0x4b, 0x06, 0xbb, 0x59, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x81, 0xc8, 0x86, 0x95, 0x15, 0xa5, 0xc5, 0x67, 0xa7, 0x56,
	0x82, 0x0d, 0xe3, 0x36, 0x92, 0xd7, 0x43, 0xf5, 0xa7, 0x1e, 0x9a, 0x19, 0x4e, 0x2c, 0x27, 0xee,
	0xc9, 0x33, 0x04, 0xf1, 0xc3, 0xf5, 0x87, 0x15, 0xa5, 0x79, 0xa7, 0x56, 0x1a, 0x6d, 0x63, 0xe4,
	0x62, 0x05, 0xdb, 0x29, 0xb4, 0x86, 0x91, 0x8b, 0x1f, 0x4d, 0x93, 0x90, 0x36, 0xba, 0xa9, 0x78,
	0xbc, 0x2a, 0xa5, 0x43, 0x9c, 0x62, 0x88, 0x5f, 0x94, 0xec, 0x9a, 0x2e, 0x3f, 0x99, 0xcc, 0x64,
	0x21, 0x64, 0xa6, 0x8f, 0x16, 0xb8, 0x18, 0x3e, 0x2c, 0xd6, 0xaf, 0xc6, 0x08, 0xc2, 0x5a, 0x27,
	0xcf, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63,
	0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0xd2, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x4a, 0x4d, 0x2d, 0xa8, 0x28, 0x29, 0x4a, 0x84,
	0x59, 0xa2, 0x9b, 0x9c, 0x5f, 0x94, 0x6a, 0xa2, 0x67, 0xa0, 0x5f, 0x01, 0xb6, 0x0e, 0x1c, 0x91,
	0x49, 0x6c, 0xe0, 0x98, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x21, 0x1f, 0x80, 0xc4, 0x47,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ValidatorVRFKey returns the registered VRF key for a given validator, if any.
	ValidatorVRFKey(ctx context.Context, in *QueryValidatorVRFKeyRequest, opts ...grpc.CallOption) (*QueryValidatorVRFKeyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ValidatorVRFKey(ctx context.Context, in *QueryValidatorVRFKeyRequest, opts ...grpc.CallOption) (*QueryValidatorVRFKeyResponse, error) {
	out := new(QueryValidatorVRFKeyResponse)
	err := c.cc.Invoke(ctx, "/steroid.vrf.v1.Query/ValidatorVRFKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ValidatorVRFKey returns the registered VRF key for a given validator, if any.
	ValidatorVRFKey(context.Context, *QueryValidatorVRFKeyRequest) (*QueryValidatorVRFKeyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ValidatorVRFKey(ctx context.Context, req *QueryValidatorVRFKeyRequest) (*QueryValidatorVRFKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorVRFKey not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ValidatorVRFKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorVRFKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorVRFKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steroid.vrf.v1.Query/ValidatorVRFKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorVRFKey(ctx, req.(*QueryValidatorVRFKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steroid.vrf.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatorVRFKey",
			Handler:    _Query_ValidatorVRFKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steroid/vrf/v1/query.proto",
}

func (m *QueryValidatorVRFKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorVRFKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorVRFKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorVRFKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorVRFKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorVRFKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValidatorVrfKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryValidatorVRFKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorVRFKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ValidatorVrfKey.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryValidatorVRFKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorVRFKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorVRFKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorVRFKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorVRFKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorVRFKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorVrfKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorVrfKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
