// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steroid/vrf/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorVRFKey is the on-chain record binding a validator to its
// registered ECVRF-EDWARDS25519-SHA512-TAI public key (D1a, Decision 2).
type ValidatorVRFKey struct {
	// validator_address is the bech32/base58-encoded operator address of the
	// validator this VRF key belongs to.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// vrf_pub_key is the raw 32-byte ECVRF-EDWARDS25519-SHA512-TAI public key.
	VrfPubKey []byte `protobuf:"bytes,2,opt,name=vrf_pub_key,json=vrfPubKey,proto3" json:"vrf_pub_key,omitempty"`
	// registered_at_height is the block height at which this key (or its most
	// recent rotation) was registered.
	RegisteredAtHeight int64 `protobuf:"varint,3,opt,name=registered_at_height,json=registeredAtHeight,proto3" json:"registered_at_height,omitempty"`
}

func (m *ValidatorVRFKey) Reset()         { *m = ValidatorVRFKey{} }
func (m *ValidatorVRFKey) String() string { return proto.CompactTextString(m) }
func (*ValidatorVRFKey) ProtoMessage()    {}
func (*ValidatorVRFKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc77e63fc13c99a, []int{0}
}
func (m *ValidatorVRFKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorVRFKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorVRFKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorVRFKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorVRFKey.Merge(m, src)
}
func (m *ValidatorVRFKey) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorVRFKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorVRFKey.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorVRFKey proto.InternalMessageInfo

func (m *ValidatorVRFKey) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorVRFKey) GetVrfPubKey() []byte {
	if m != nil {
		return m.VrfPubKey
	}
	return nil
}

func (m *ValidatorVRFKey) GetRegisteredAtHeight() int64 {
	if m != nil {
		return m.RegisteredAtHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorVRFKey)(nil), "steroid.vrf.v1.ValidatorVRFKey")
}

func init() { proto.RegisterFile("steroid/vrf/v1/types.proto", fileDescriptor_fbc77e63fc13c99a) }

var fileDescriptor_fbc77e63fc13c99a = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0x49, 0x2d,
	0xca, 0xcf, 0x4c, 0xd1, 0x2f, 0x2b, 0x4a, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0x2c, 0x48, 0x2d,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0xca, 0xe9, 0x95, 0x15, 0xa5, 0xe9, 0x95,
	0x19, 0x4a, 0x49, 0x26, 0xe7, 0x17, 0xe7, 0xe6, 0x17, 0xc7, 0x83, 0x65, 0xf5, 0x21, 0x1c, 0x88,
	0x52, 0xa5, 0xcd, 0x8c, 0x5c, 0xfc, 0x61, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0xf9, 0x45, 0x61,
	0x41, 0x6e, 0xde, 0xa9, 0x95, 0x42, 0x7e, 0x5c, 0x82, 0x65, 0x30, 0xa1, 0xf8, 0xc4, 0x94, 0x94,
	0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x4e, 0x27, 0xc5, 0x4b, 0x5b, 0x74, 0x65,
	0xa1, 0x06, 0xc0, 0xb5, 0x39, 0x42, 0x94, 0x04, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x07, 0x09, 0x94,
	0xa1, 0x89, 0x0b, 0xc9, 0x71, 0x71, 0x97, 0x15, 0xa5, 0xc5, 0x17, 0x94, 0x26, 0xc5, 0x67, 0xa7,
	0x56, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x71, 0x96, 0x15, 0xa5, 0x05, 0x94, 0x26, 0x81,
	0xec, 0x33, 0xe0, 0x12, 0x29, 0x4a, 0x4d, 0xcf, 0x04, 0x39, 0x3a, 0x35, 0x25, 0x3e, 0xb1, 0x24,
	0x3e, 0x23, 0x35, 0x33, 0x3d, 0xa3, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x48, 0x08, 0x21,
	0xe7, 0x58, 0xe2, 0x01, 0x96, 0x71, 0xf2, 0x3c, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6,
	0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39,
	0x86, 0x28, 0xfd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xa4, 0xd4,
	0xd4, 0x82, 0x8a, 0x92, 0xa2, 0x44, 0x7d, 0x68, 0x70, 0xe8, 0x26, 0xe7, 0x17, 0xa5, 0x9a, 0xe8,
	0x19, 0xe8, 0x57, 0x80, 0x03, 0x0d, 0x1c, 0x62, 0x49, 0x6c, 0xe0, 0x70, 0x30, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x26, 0xd3, 0x10, 0xb2, 0x50, 0x01, 0x00, 0x00,
}

func (m *ValidatorVRFKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorVRFKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorVRFKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisteredAtHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RegisteredAtHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.VrfPubKey) > 0 {
		i -= len(m.VrfPubKey)
		copy(dAtA[i:], m.VrfPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VrfPubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorVRFKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VrfPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisteredAtHeight != 0 {
		n += 1 + sovTypes(uint64(m.RegisteredAtHeight))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorVRFKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorVRFKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorVRFKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfPubKey = append(m.VrfPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfPubKey == nil {
				m.VrfPubKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAtHeight", wireType)
			}
			m.RegisteredAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
